/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: stanleyatabiishabor (https://sketchfab.com/stanleyatabiishabor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-b220d3f7900f49b6a0d1f0ad15e2d1df
Title: javascript
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/javascript.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Scene_-_Root']}
        position={[0.438, -0.013, 0.017]}
        rotation={[1.574, 0, -3.076]}
        scale={[1.376, 1.002, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/javascript.glb')
