/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/octocat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_bf694e53-628f-4be9-a751-d3b939e0d907'].geometry}
        material={materials['tripo_mat_bf694e53-628f-4be9-a751-d3b939e0d907']}
      />
    </group>
  )
}

useGLTF.preload('/models/octocat.glb')